
# video configurations
MANIFEST = "Manifest.json"
VIDEO_SIZE_FILE = "video_size_"
NUM_OF_CHUNKS = "NUM_OF_CHUNKS"
BITRATE_LEVELS = "BITRATE_LEVELS"
VIDEO_CHUNK_LENGTH = "VIDEO_CHUNK_LENGTH"
BR_DIM = "BR_DIM"
VIDEO_SIZES = "VIDEO_SIZES"
BITRATE_SIZE_RATIO = "BITRATE_SIZE_RATIO"
HD_REWARD = "HD_REWARD"

# player configurations
BUFFER_CAPACITY = "BUFFER_CAPACITY"

# trace parameters
TIME = "TIME"
BANDWIDTH = "BANDWIDTH"
FILE_NAMES = "FILE_NAMES"

# environment parameters
TRAIN = "TRAIN"
TEST = "TEST"

# QoE functions
LOG = 'log'
LIN = 'lin'
HD = 'hd'
SMOOTH_PENALTY = 1.

BOGGART_CONTEXT = "BoggartContext"

LAST_BR_IDX = 0
BUFFER_IDX = 1
THROUGHPUT_IDX = 2
DELAY_IDX = 3
NEXT_CHUNKS_START_IDX = 4
CHUNKS_TILL_END_IDX = 5


M_IN_K = 1000.0
MILLISECONDS_IN_SECOND = 1000.0
B_IN_MB = 1000000.0
BITS_IN_BYTE = 8.0
RANDOM_SEED = 42
BUFFER_NORM_FACTOR = 10.0
MAX_REBUF = 10.
DEFAULT_QUALITY = 1
FLAT_INPUT_LEN = 11
INPUT_LEN = 6
HISTORY_LEN = 8
BUFFER_CAPACITY = 60.0

LIN_REBUF_PENALTY = 4.3
LOG_REBUF_PENALTY = 2.66
HD_REBUF_PENALTY = 8.0

BOGGART = "boggart"
BOLA = "bola"
THROUGHPUT = "throughput"
PENSIEVE = "pensieve"
MPC = "mpc"
BBA = "bba"